### PR TITLE
Fix Multi-Tenant guide mistake

### PR DESCRIPTION
**Pull request by LvLs9**
Fix double-and

### CODE REVIEW

**Review by hasheddan — CHANGES_REQUESTED** [review]
Thanks @LvLs9! Could you add sign off to your commit? Helpful guide here: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Review by hasheddan — COMMENTED** [review]
@LvLs9 looks like you may still be missing sign off here

**Comment by hasheddan** [comment]
@LvLs9 `git commit —amend —signoff` and then a force push should get this working

**Comment by LvLs9** [comment]
Not sure I got how it works, but looks like checks passed 🙄😄 Sorry for that

**Review by hasheddan — APPROVED** [review]
LGTM — thanks for fixing this @LvLs9!

**Pull request merged**
