### PR TITLE
Shorten Guide Entry Title

### PR DESCRIPTION
**Pull request by natereid72**
### Description of your changes
The title of the self-signed cert was too long for the formatting of the docs web page. Made it shorter for better page layout.

I have:

- [x ] Read and followed Crossplane's [contribution process].
- [x ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
Thanks @natereid72! I added the 1.7 backport label, would you mind rebasing to drop the merge commit?

**Comment by natereid72** [comment]
Sorry about that @hasheddan , I should have just made a fresh fork. I said I rebased the PR but it didn't look like it changed anything. Let me know if it still needs attention

**Review by hasheddan — APPROVED** [review]
Looks good, thanks @natereid72!

**Comment by luebken** [comment]
Thanks Nate.

**Pull request merged**
