### PR TITLE
feat(skip): skip sub deps in configuration.meta.pkg

### LINKED ISSUE #5279: Proposal: Introduction of `skipDependencyResolution` Field for dependsOn in `Configurations`
### What problem are you facing?

This proposal suggests introducing a `skipDependencyResolution` field for the `dependsOn` attribute within configurations. In current practice, dependency resolution can be skipped only at a global configuration level. However, this often does not suffice for the nuanced needs of complex platform projects, especially in large companies where fulfilling all dependencies in a configuration can be challenging (Security, External Registries, same APIs Inhouse with additional features). The proposed feature aims to provide more granular control over dependency resolution within individual configurations.

Many companies, especially those with large platform projects, frequently encounter difficulties in managing dependencies within their configurations. The current approach allows for skipping dependency resolution for the entire configuration, which is often a blunt tool for what requires a more precise solution. https://doc.crds.dev/github.com/crossplane/crossplane/pkg.crossplane.io/Configuration/v1@v1.14.5#spec-skipDependencyResolution

### How could Crossplane help solve your problem?

The proposed solution is to introduce a new field, `skipDependencyResolution`, that can be used within the `dependsOn` attribute in configuration. This field would allow platform builders to specify if dependency resolution should be skipped for particular dependencies, rather than applying this skip to the entire configuration.

```
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: test-configuration
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
      version: "v0.5.0"
      skipDependencyResolution: true
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
      version: "v0.5.0"
      skipDependencyResolution: true
    - provider: xpkg.upbound.io/upbound/provider-aws-sqs
      version: "v0.47.1"
    - provider: xpkg.upbound.io/upbound/provider-aws-cloudwatchevents
      version: "v0.47.1"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: "v0.16.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: "v0.10.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-ec2
      version: "v0.47.1"
    - provider: xpkg.upbound.io/upbound/provider-aws-eks
      version: "v0.47.1"
    - provider: xpkg.upbound.io/upbound/provider-aws-iam
      version: "v0.47.1"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      version: "v0.2.1"
```

The primary benefit of this feature is the increased control it offers platform builders over their configurations. By allowing dependency resolution to be skipped on a per-dependency basis, teams can manage their configurations more effectively, especially in scenarios where certain dependencies are known to be unnecessary or problematic. This flexibility is particularly valuable in large-scale platform projects where managing a vast number of dependencies can be challenging.

### Implementation Considerations

- This change should be backward compatible, not affecting existing configurations that do not use the new field.
- Care must be taken to ensure that the introduction of this field does not introduce unexpected behavior in dependency resolution in package manager
- Documentation and examples should be updated to reflect this new feature.

### PR DESCRIPTION
**Pull request by haarchri**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/5279

This PR introduces a new feature: a `skipDependencyResolution` boolean in `Configuration.meta.pkg.crossplane.io`. This allows package authors to choose whether to install an API from a dependency without installing the dependencies of that configuration. This is particularly useful in a few scenarios. 

- if someone is customizing reference platforms, it's not necessary to install a dependency that includes the same API ex. cluster.aws.platformref.company.com (https://github.com/upbound/configuration-aws-eks-irsa/blob/main/crossplane.yaml#L13), as it would create conflicts/ gets overridden. However, they might still want to utilize the API from a configuration while managing the dependencies themselves. 
- another scenario is when providers are hardcoded, as in reference platforms (https://github.com/upbound/configuration-aws-eks/blob/main/crossplane.yaml#L24), which makes it challenging for external users to adopt our validated configurations due to provider version constraints. This update facilitates using the API while independently managing dependencies.

### test skipDependencyResolution: true
```
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: test-5279
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
      version: "v0.3.0"
      skipDependencyResolution: true
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
      version: "v0.4.0"
      skipDependencyResolution: true
```

Remember, we updated the configuration.meta.pkg, so if you're planning to test this implementation, you need to use crank from this PR for building and pushing. Otherwise, the new skipDependencyResolution feature will be ignored during the build process.

```
./crank xpkg build -f xpkg
./crank xpkg push docker.io/haarchri/test-5279:v0.0.2 -f xpkg/test.xpkg
```

```
kubectl apply -f test-5279.yaml
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: test-5279
spec:
  package: docker.io/haarchri/test-5279:v0.0.2
```

```
kubectl get configurations
NAME                                      INSTALLED   HEALTHY   PACKAGE                                                          AGE
test-5279                                 True        True      docker.io/haarchri/test-5279:v0.0.2                              31m
upbound-configuration-aws-eks-irsa        True        True      xpkg.upbound.io/upbound/configuration-aws-eks-irsa:v0.4.0        31m
upbound-configuration-aws-eks-karpenter   True        True      xpkg.upbound.io/upbound/configuration-aws-eks-karpenter:v0.3.0   31m
```

```
kubectl get lock lock -o yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Lock
metadata:
  creationTimestamp: "2024-01-25T07:53:18Z"
  finalizers:
  - lock.pkg.crossplane.io
  generation: 114
  name: lock
  resourceVersion: "72630"
  uid: cf230c55-b558-48c0-b040-5e402912a7c8
packages:
- dependencies:
  - constraints: v0.3.0
    package: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
    skipDependencyResolution: true
    type: Configuration
  - constraints: v0.4.0
    package: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
    skipDependencyResolution: true
    type: Configuration
  name: test-5279-3bc7827d404b
  source: docker.io/haarchri/test-5279
  type: Configuration
  version: v0.0.2
- dependencies: [] # <-- skipped sub-dependencies
  name: upbound-configuration-aws-eks-karpenter-3a5c53ea379b
  source: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
  type: Configuration
  version: v0.3.0
- dependencies: [] # <-- skipped sub-dependencies
  name: upbound-configuration-aws-eks-irsa-c7bb9a33f059
  source: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
  type: Configuration
  version: v0.4.0

```

### test skipDependencyResolution: false / default behaviour

```
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: test-5279
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
      version: "v0.3.0"
    - configuration: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
      version: "v0.4.0"
```

```
kubectl get configuration
NAME                                      INSTALLED   HEALTHY   PACKAGE                                                          AGE
test-5279-without-skip                    True        True      docker.io/haarchri/test-5279-without-skip:v0.0.2                 9m25s
upbound-configuration-aws-eks             True        True      xpkg.upbound.io/upbound/configuration-aws-eks:v0.6.0             9m1s
upbound-configuration-aws-eks-irsa        True        True      xpkg.upbound.io/upbound/configuration-aws-eks-irsa:v0.4.0        9m15s
upbound-configuration-aws-eks-karpenter   True        True      xpkg.upbound.io/upbound/configuration-aws-eks-karpenter:v0.3.0   9m20s
upbound-configuration-aws-network         True        True      xpkg.upbound.io/upbound/configuration-aws-network:v0.8.0         8m51s
```

```
apiVersion: pkg.crossplane.io/v1beta1
kind: Lock
metadata:
  creationTimestamp: "2024-01-25T16:22:40Z"
  finalizers:
  - lock.pkg.crossplane.io
  generation: 15
  name: lock
  resourceVersion: "80384"
  uid: ffd097fb-4e45-48eb-a4ed-6e7c331fc3b6
packages:
- dependencies:
  - constraints: v0.6.0
    package: xpkg.upbound.io/upbound/configuration-aws-eks
    skipDependencyResolution: false
    type: Configuration
  name: upbound-configuration-aws-eks-irsa-c7bb9a33f059
  source: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
  type: Configuration
  version: v0.4.0
- dependencies: []
  name: crossplane-contrib-provider-kubernetes-63506a3443e0
  source: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
  type: Provider
  version: v0.10.0
- dependencies:
  - constraints: v0.8.0
    package: xpkg.upbound.io/upbound/configuration-aws-network
    skipDependencyResolution: false
    type: Configuration
  - constraints: v0.16.0
    package: xpkg.upbound.io/crossplane-contrib/provider-helm
    skipDependencyResolution: false
    type: Provider
  - constraints: v0.10.0
    package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
    skipDependencyResolution: false
    type: Provider
  - constraints: v0.47.1
    package: xpkg.upbound.io/upbound/provider-aws-ec2
    skipDependencyResolution: false
    type: Provider
  - constraints: v0.47.1
    package: xpkg.upbound.io/upbound/provider-aws-eks
    skipDependencyResolution: false
    type: Provider
  - constraints: v0.47.1
    package: xpkg.upbound.io/upbound/provider-aws-iam
    skipDependencyResolution: false
    type: Provider
  - constraints: v0.2.1
    package: xpkg.upbound.io/upbound/function-patch-and-transform
    skipDependencyResolution: false
    type: Function
  name: upbound-configuration-aws-eks-57a8d05998b7
  source: xpkg.upbound.io/upbound/configuration-aws-eks
  type: Configuration
  version: v0.6.0
- dependencies: []
  name: upbound-provider-family-aws-fec919bd2218
  source: xpkg.upbound.io/upbound/provider-family-aws
  type: Provider
  version: v0.47.1
- dependencies:
  - constraints: '>= 0.0.0'
    package: xpkg.upbound.io/upbound/provider-family-aws
    skipDependencyResolution: false
    type: Provider
  name: upbound-provider-aws-eks-cccfc6cdebd0
  source: xpkg.upbound.io/upbound/provider-aws-eks
  type: Provider
  version: v0.47.1
- dependencies:
  - constraints: '>= 0.0.0'
    package: xpkg.upbound.io/upbound/provider-family-aws
    skipDependencyResolution: false
    type: Provider
  name: upbound-provider-aws-iam-fc4c8e7f6d42
  source: xpkg.upbound.io/upbound/provider-aws-iam
  type: Provider
  version: v0.47.1
- dependencies:
  - constraints: '>= 0.0.0'
    package: xpkg.upbound.io/upbound/provider-family-aws
    skipDependencyResolution: false
    type: Provider
  name: upbound-provider-aws-ec2-64262f355830
  source: xpkg.upbound.io/upbound/provider-aws-ec2
  type: Provider
  version: v0.47.1
- dependencies:
  - constraints: v0.3.0
    package: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
    skipDependencyResolution: false
    type: Configuration
  - constraints: v0.4.0
    package: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
    skipDependencyResolution: false
    type: Configuration
  name: test-5279-without-skip-63b55fa85b78
  source: docker.io/haarchri/test-5279-without-skip
  type: Configuration
  version: v0.0.2
- dependencies:
  - constraints: v0.47.1
    package: xpkg.upbound.io/upbound/provider-aws-ec2
    skipDependencyResolution: false
    type: Provider
  - constraints: v0.2.1
    package: xpkg.upbound.io/upbound/function-patch-and-transform
    skipDependencyResolution: false
    type: Function
  name: upbound-configuration-aws-network-d28b67b562a1
  source: xpkg.upbound.io/upbound/configuration-aws-network
  type: Configuration
  version: v0.8.0
- dependencies:
  - constraints: 0.4.0
    package: xpkg.upbound.io/upbound/configuration-aws-eks-irsa
    skipDependencyResolution: false
    type: Configuration
  - constraints: v0.47.1
    package: xpkg.upbound.io/upbound/provider-aws-sqs
    skipDependencyResolution: false
    type: Provider
  - constraints: v0.47.1
    package: xpkg.upbound.io/upbound/provider-aws-cloudwatchevents
    skipDependencyResolution: false
    type: Provider
  name: upbound-configuration-aws-eks-karpenter-3a5c53ea379b
  source: xpkg.upbound.io/upbound/configuration-aws-eks-karpenter
  type: Configuration
  version: v0.3.0
- dependencies: []
  name: crossplane-contrib-provider-helm-b4cc4c2c8db3
  source: xpkg.upbound.io/crossplane-contrib/provider-helm
  type: Provider
  version: v0.16.0
- dependencies:
  - constraints: '>= 0.0.0'
    package: xpkg.upbound.io/upbound/provider-family-aws
    skipDependencyResolution: false
    type: Provider
  name: upbound-provider-aws-cloudwatchevents-582f50b0ba8d
  source: xpkg.upbound.io/upbound/provider-aws-cloudwatchevents
  type: Provider
  version: v0.47.1
- dependencies: []
  name: upbound-function-patch-and-transform-a2f88f8d8715
  source: xpkg.upbound.io/upbound/function-patch-and-transform
  type: Function
  version: v0.2.1
- dependencies:
  - constraints: '>= 0.0.0'
    package: xpkg.upbound.io/upbound/provider-family-aws
    skipDependencyResolution: false
    type: Provider
  name: upbound-provider-aws-sqs-a48f3c4bece9
  source: xpkg.upbound.io/upbound/provider-aws-sqs
  type: Provider
  version: v0.47.1
```

Fixes #5279

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added or updated unit tests.
- [ ] Added or updated e2e tests.
- [x] Linked a PR or a [docs tracking issue] to [document this change].
- [x] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Comment by haarchri** [comment]
will check unit-tests

**Comment by negz** [comment]
Thanks @haarchri!

Let's hold this for v1.16. We're at feature freeze for v1.15 and there's ongoing discussion in #5279 about how this should work.

**Comment by negz** [comment]
Quoting @bobh66:

> It seems a little odd to specify this inside the definition of the Configuration itself - it seems like something that the package deployer would want to control more than the package author.

I agree with this. Wouldn't this be an install-time consideration, not authoring-time?

**Comment by haarchri** [comment]
If Ichoose to use a configuration while authoring and decide to skip the dependencies because I have older or newer versions from providers or functions, and i won't have to replicate the entire composition and definition code when i have an option to skip ... during install time is to late without this information

**Comment by bobh66** [comment]
> If Ichoose to use a configuration while authoring and decide to skip the dependencies because I have older or newer versions from providers or functions, and i won't have to replicate the entire composition and definition code when i have an option to skip ... during install time is to late without this information

Just to make sure I understand - you are authoring a Configuration that is referencing another existing Configuration that has dependencies, and as the author you know that you have already satisfied the dependencies of that Configuration so you want to be able to tell the package manager to skip those dependencies?  This is probably what you are saying in the description above, right?

**Comment by haarchri** [comment]
Yes let's say i want to skip because i have a newer version for a provider already running so i don't need the dependecies because package manager will not install if someone pinned the version..

**Comment by bobh66** [comment]
Thanks, that makes sense now.  It could definitely cause problems if the author doesn't satisfy the dependencies, but hopefully the errors would be clear enough to describe the situation and it's cause.

**Pull request closed without merging**
