### PR TITLE
Add the pkg directory to GO_SUBDIRS

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

There's failing unit tests in there, but we never run them because `make test` ignores them.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Comment by negz** [comment]
@phisco TIL. 😬

**Review by jbw976 — COMMENTED** [review]
Seems like a reasonable thing to add - what do you want to see before moving this PR out of draft?

**Comment by negz** [comment]
@jbw976 We need to get the failing unit tests to pass, but I'm looking into something else and don't want to get sidetracked with that right now.

**Comment by phisco** [comment]
🤦‍♂️ I'm off a few days, I'll have a look at it early next week if no one gets to it faster

**Comment by jbw976** [comment]
I was able to debug the first failing unit test `TestComposedTemplateGetBaseObject` and I've pushed a commit for that: https://github.com/crossplane/crossplane/pull/5708/commits/94dac8e2e7d3298f824b67ce7a450d2ce3eb5b7a

Stepping through that failing test in the debugger showed that it had the exact same behavior @negz described in https://github.com/crossplane/crossplane/issues/4970. When we added DeepCopy methods for Unstructured types in https://github.com/crossplane/crossplane-runtime/pull/599, `GetBaseObject` started correctly returning the full `composed.Unstructured` type, instead of the embedded `unstructured.Unstructured` type that this test was expecting.

Now the test expects for the correct `composed.Unstructured` type. I'll try to look at the other failing tests soon too! 🙏

**Comment by jbw976** [comment]
I've got all unit tests passing locally now and I've pushed commits for each fix. Let's see if the unit tests check goes green on this PR now! 🟢 🙏

**Comment by jbw976** [comment]
Unit tests are green! https://github.com/crossplane/crossplane/actions/runs/9144355934/job/25142101609?pr=5708

Moving this PR out of draft 🫡

**Review by jbw976 — APPROVED** [review]
all these fixes make sense to me, but i'll leave @negz or @phisco to merge if they are satisfied with the test fixes!

**Review by negz — COMMENTED** [review]
LGTM, thanks @jbw976!

**Pull request merged**
