### PR TITLE
feat: added customAnnotations to RBAC Manager

### PR DESCRIPTION
**Pull request by pierluigilenoci**
Added customAnnotations to RBAC Manager

### Description of your changes

This change allows to add custom annotations to RBAC Manager.

Fixes https://github.com/crossplane/crossplane/issues/5246

Copied from:
- https://github.com/upbound/universal-crossplane/issues/419
- https://github.com/upbound/universal-crossplane/pull/420

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [x] Added or updated e2e tests.
- [x] Linked a PR or a [docs tracking issue] to [document this change].
- [x] Added `backport release-x.y` labels to auto-backport this PR.

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@phisco @negz @turkenh, please take a look.

**Review by phisco — APPROVED** [review]

**Comment by pierluigilenoci** [comment]
@phisco, thanks for the approval, but one test failed, probably for a timeout. Could you please restart the test?

**Review by turkenh — APPROVED** [review]

**Comment by turkenh** [comment]
> @phisco, thanks for the approval, but one test failed, probably for a timeout. Could you please restart the test?

Unfortunately, we have a sporadic with that one. Safe to ignore in this PR.

**Comment by pierluigilenoci** [comment]
@phisco nevermind! 😝 
@turkenh, thank you! ❤️

**Pull request merged**
