### PR TITLE
adding Neux to ADOPTERS

### PR DESCRIPTION
**Pull request by styk-tv**
Signed-off-by: Peter Styk <peter@styk.tv>

### Description of your changes

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by jbw976** [comment]
Awesome @styk-tv, thanks for taking the time to make this contribution and sharing your crossplane usage!! 💪 

We're merging these PRs in the order that they were submitted, so yours will be after https://github.com/crossplane/crossplane/pull/3725 - once that PR is merged, you'll have a merge conflict to resolve. I'll ping you when it's your turn to do the merge conflict dance 😂

let me know if you want me to handle the conflict when it's time, I'm happy to do that also!

**Comment by styk-tv** [comment]
@jbw976 thanks for the message Jared. I can resolve the conflict when it arrives no issue. Just send a ping when its my turn.

**Comment by jbw976** [comment]
@styk-tv #3725 has now been merged, so it's now time to resolve the merge conflict.  I tried to take care this burden off your hands, but looks like I didn't have permissions to do so on this particular PR :)

Let me know if I can help get the merge conflicts resolved and we'll then get this PR merged in ASAP, thank you!

**Comment by styk-tv** [comment]
@jbw976 this should be now in sync

**Review by jbw976 — APPROVED** [review]
wonderful, thank you for your follow through on this PR @styk-tv and good to see you today! 👋

**Pull request merged**
