### PR TITLE
minor fixes in the introduction documents

### PR DESCRIPTION
**Pull request by horis233**
### Description of your changes

This PR is for two minor fixes in the introduction documents:
- Fixes typos in the named links
- Update "Defining Infrastructure"

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
LGTM! Thanks @horis233! Would you mind rebasing?

**Comment by horis233** [comment]
Sure, I will cherry-pick this commit to the release-1.0 branch.

**Comment by hasheddan** [comment]
@horis233 thanks! This PR also needs a rebase on `master` as well though :+1:

**Comment by horis233** [comment]
@hasheddan This PR has been rebased on the `master` branch.

**Comment by horis233** [comment]
I am curious if it is necessary to rebase this PR. It looks like there is no conflict with the upstream.

**Comment by hasheddan** [comment]
@horis233 it is only because the merge rule is set up for branch to be strictly ahead. We may revisit this in the future because it is annoying in situations like this :sweat_smile:

**Pull request merged**
