### PR TITLE
feat(crank): add marketplace login/logout commands and enable push.

### LINKED ISSUE #4785: Support pushing packages to xpkg.upbound.io
### What problem are you facing?

The xpkg.upbound.io is a very common place to push Crossplane packages. It's the only "Crossplane-aware" registry I know of, in that valid packages are indexed and appear with documentation etc at https://marketplace.upbound.io.

Right now it's not clear to me whether it's possible to authenticate to xpkg.upbound.io using the `crossplane` CLI.

### How could Crossplane help solve your problem?

Make it possible to authenticate and push to xpkg.upbound.io, ideally without needing to install extra configuration or binaries (e.g. `docker-credential-up` from https://github.com/upbound/up).

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Fixes #4785.

Mostly importing the code from upbound/up, with some minor simplifications to reduce the number of packages to copy over.

The following workflow now works:
```shell
$ crank marketplace login
Username: ...
Password:
Login successful.
$ crank xpkg push -f test-platform-ref-aws.xpkg xpkg.upbound.io/...
$ crank marketplace logout
```

I ended up using the same `.up/config.json` file, we can switch it and maybe simplify it a bit later on.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Added or updated unit **and** E2E tests for my change.
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR, if necessary.~
- [ ] ~Opened a PR updating the [docs], if necessary.~

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

**Comment by negz** [comment]
I saw @jbw976 suggested `crossplane xpkg login`. I'd prefer that to `crossplane marketplace`. It feels more seamless to `crossplane xpkg build && crossplane xpkg login && crossplane push`. I think making the default "target" for `crossplane xpkg` xpkg.upbound.io would be reasonable - i.e. making that our default push registry.

**Comment by jbw976** [comment]
yes i have a preference for `crossplane xpkg login` myself too 👍

**Comment by phisco** [comment]
Yes, marketplace didn't feel great to me neither, but according to the discussion going on in https://github.com/crossplane/crossplane/issues/4787#issuecomment-1765776942, there won't be an xpkg subcommand anymore.

**Comment by negz** [comment]
We all chatted and reached alignment that this should be `crossplane xpkg login`, per https://github.com/crossplane/crossplane/issues/4787#issuecomment-1766979905. However it's late for @phisco so we agreed we'll merge this and I'll open a follow-on PR to rearrange everything.

**Review by negz — APPROVED** [review]

**Pull request merged**
