### PR TITLE
Move TargetRef to K8s App Spec and update workload controllers to modern patterns

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Because `targetRef` cannot be reliably reproduced for `KubernetesApplication` and `KubernetesApplicationResource`, it should be in the `spec` instead of the `status`. While making this update, I also noticed that we had not moved to using `subresource:status` for our `workload` types. The types have been updated and the controllers are refactored to accommodate and implement patterns that are more consistent with rest of the Crossplane ecosystem.

As a byproduct of moving the `targetRef` to the `spec`, users and systems can now pick a specific `KubernetesTarget` directly as opposed to previously only being able to rely on the scheduler matching based on labels.

### How has this code been tested?

These controllers have significant unit testing implemented, but further manual testing will be included here as it is executed.

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [ ] Updated any relevant [documentation] and [examples].
- [ ] Reported all new error conditions into the log or as an event, as
  appropriate.

For more about what we believe makes a pull request complete, see our
[definition of done].

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[definition of done]: https://github.com/crossplane/crossplane/tree/master/design/one-pager-definition-of-done.md

### CODE REVIEW

**Comment by hasheddan** [comment]
@negz it would probably be good to add eventing and some other more modern patterns here as well. I am happy to either include in this PR or follow-up with those changes.

**Comment by hasheddan** [comment]
@negz SGTM! Thanks for the review :)

**Comment by muvaf** [comment]
Is this tested manually? Just wanted to check because spec/status call stuff is hard to catch in unit tests.

**Comment by hasheddan** [comment]
@muvaf yep! I will also make sure to get the follow-up PR in soon and show some additional testing there 👍

**Pull request merged**
