### PR TITLE
Remove the RBAC namespace controller

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/5227

I'm confident no-one uses this controller. It's been disabled by default since Crossplane v1.13, and since v1.15 anyone who tries to enable it would get an error linking to the deprecation tracking issue (https://github.com/crossplane/crossplane/pull/5260). No-one has raised any concerns about removing it.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Review by phisco — APPROVED** [review]
LGTM 🙏

**Comment by jeremypng** [comment]
I guess the ship has probably sailed on this one, but we are using option 4 above to control accepting claims in a particular namespace.

We create an Azure User Assigned Identity->Federated Identity->AKS Service Account that has the namespaced rolebinding of crossplane-admin and then use the namespace annotations to control what claims are allowed to be managed in that namespace by that user.

The feature actually works really well and allows our web app to securely manage Azure infrastructure without having carte blanche access to the crossplane API or the Azure API. So in theory, if our webapp was compromised, the bad actors would only have access to the predetermined claim definitions in Azure (bad enough, but not enough to take over the subscription).

**Comment by negz** [comment]
@jeremypng Yes unfortunately the ship has sailed. From what I can gather you may have been the only folks using this feature. Sorry!

FWIW I think this controller was pretty self-contained, so if you're up for maintaining it it should be relatively straightforward to take the code that was deleted in this PR and package it up as a standalone controller that can be deployed alongside Crossplane. I'd be happy for that to live in crossplane-contrib if anyone is interested in maintaining it.

**Comment by jeremypng** [comment]
I think it would be easier for us to just create a role for our Crossplane claims and apply that rolebinding to the user instead of the crossplane-admin role. We're not in a position to take on ownership of that code. At the end of the day, I guess the RBAC controller was just a convenience method. As much YAML as we have, what's a few hundred more lines... Thanks for the response.

**Comment by benzaidfoued** [comment]
@negz ,That controller was pretty useful for us ,is there a way to add it back ?! i'm asking as i see multiple discussions around RBAC without final solution ( except the basic one ) .

**Pull request merged**
