### PR TITLE
A little more retroactive documentation polish

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

Small updates; see each commit message for details.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
LGTM! Thanks @negz!

**Comment by hasheddan** [comment]
@negz would you mind cherry picking this to `release-0.13`? :)

**Comment by negz** [comment]
I would not! Is https://github.com/crossplane/crossplane/pull/1836 ready to merge? I was thinking we could cherry pick both in the one PR.

**Comment by hasheddan** [comment]
Good idea! I think it still needs to be updated so that each of the `definition.yaml` files are not deleted

**Pull request merged**
