### PR TITLE
Fixed a grammatical error/typo in the faqs docs.

### PR DESCRIPTION
**Pull request by jbrawdy**
### Description of your changes

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

No testing has been done as this small typo fix.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by jbrawdy** [comment]
> LGTM! Thanks @jbrawdy!

No problem!

**Comment by hasheddan** [comment]
@jbrawdy apologies for the delay here :/ It appears Jenkins is having trouble building this very old release branch of Crossplane. I think it is likely that we will not update this release branch to fix this given it is well out of support at this point. Would you be okay with closing out this PR? Happy to help you get started with other contributions if you are interested :)

**Comment by jbrawdy** [comment]
> @jbrawdy apologies for the delay here :/ It appears Jenkins is having trouble building this very old release branch of Crossplane. I think it is likely that we will not update this release branch to fix this given it is well out of support at this point. Would you be okay with closing out this PR? Happy to help you get started with other contributions if you are interested :)

No worries. I think closing the PR makes sense. I realized after I created the pull request that this was old version.
But I am interested in other ways I could contribute. What did you have in mind?

**Comment by hasheddan** [comment]
@jbrawdy I will ping you in Slack :)

**Pull request closed without merging**
