### PR TITLE
Build configuration packages with v1alpha1 meta types

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Reverts update to build configuration packages with v1 meta types and
uses v1alpha1 for the time being, which are still supported in the
package manager.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

`kubectl crossplane build configuration ...`

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by negz — COMMENTED** [review]
@hasheddan is it possible to temporarily decouple the Configuration push from our docs? i.e. To (manually?) build and push `v1alpha1` packages that the Upbound Registry will accept, but keep the docs referring to `v1` metadata?

**Comment by hasheddan** [comment]
@negz yep we could do that! We could also keep pushing them and just pin the install command to previously built version. Do you have a preference?

**Comment by negz** [comment]
> Do you have a preference?

I don't think so - happy to go with whatever is easiest.

That said, will we need to pin the provider deps of these configs in the v1 release branch such that they won't resolve their provider dependencies to RC providers? I imagine that would require a manual package build.

**Comment by hasheddan** [comment]
We could just update the action to only on workflow dispatch and do manual builds if needed. We should probably make all versions just depend on stable versions of their providers though, in which case continuing to build on merges would work fine I think.

**Comment by hasheddan** [comment]
@negz all the configurations' dependencies have now been updated to require a stable version :+1:

**Review by negz — APPROVED** [review]

**Pull request merged**
