### PR TITLE
crank/trace: fix order of column to match managed resources

### PR DESCRIPTION
**Pull request by sttts**
### Description of your changes

Crossplane resources via kubectl show SYNCED READY in that order. Let's keep our mind sane by using the same order in the trace command :)

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added or updated unit tests.
- [ ] ~~Added or updated e2e tests.~~
- [ ] ~~Linked a PR or a [docs tracking issue] to [document this change].~~
- [ ] ~~Added `backport release-x.y` labels to auto-backport this PR.~~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Review by phisco — APPROVED** [review]
Makes sense to me! 🙏

**Comment by phisco** [comment]
Oops, you need to update the default output in the tests.

**Comment by sttts** [comment]
> Oops, you need to update the default output in the tests.

Done. Tedious :D

**Comment by phisco** [comment]
> > Oops, you need to update the default output in the tests.
> 
> Done. Tedious :D

totally agree, I think I saw a library that was automatically regenerating golden files for tests on failures if requested to do so, but IIRC that didn't play well with our pattern for tests. We can address that later if we feel it's causing too much pain

**Pull request merged**
