### PR TITLE
Move releases to the new Crossplane Community Calendar

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

We'd like to consolidate all our various events/meetings into one shared calendar for the Crossplane community. Step one is removing the releases calendar to the new Crossplane Community Calendar.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

N/A

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
Thanks @negz!

**Review by jbw976 — APPROVED** [review]
Thanks for getting this community calendar set up @negz!

**Review by muvaf — APPROVED** [review]
Thanks!

**Comment by muvaf** [comment]
The release calendar is already emptied, so there is no link for users other than the one in this PR. I'll merge this PR now so that people can access it easily.

**Pull request merged**
