### PR TITLE
Add OpenSSF scorecard badge to README.md

### PR DESCRIPTION
**Pull request by jeanduplessis**
### Description of your changes

Adds the OpenSFF Scorecard badge to the README file to comply with the CLOMonitor check: https://clomonitor.io/docs/topics/checks/#openssf-scorecard-badge

Part of https://github.com/crossplane/crossplane/issues/4963

I have: 

- [X] Read and followed Crossplane's [contribution process].
- [ ] ~Run `make reviewable` to ensure this PR is ready for review.~
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Review by phisco — APPROVED** [review]

**Review by jbw976 — COMMENTED** [review]
is this necessary in addition to the OpenSSF best practices badge that was already added in #5231? 🤔

**Comment by jeanduplessis** [comment]
Unfortunately, it is. They use separate regex checks:
CleanShot 2024-01-17 at 07 48 02@2x

If you look at https://github.com/kyverno/kyverno it also has both.
CleanShot 2024-01-17 at 07 48 38@2x

**Comment by harshitasao** [comment]
According to the [scorecard action docs](https://github.com/ossf/scorecard-action#:~:text=scorecard.dev.-,Scorecard%20Badge,-Starting%20with%20scorecard), it is better to update the domain of the badge and score.

**Pull request closed without merging**
