### PR TITLE
Make `spec.controller.image` in `Provider.meta.pkg.crossplane.io` optional and default to self

### LINKED ISSUE #2757: Make `spec.controller.image` in `Provider.meta.pkg.crossplane.io` optional and default to self
### What problem are you facing?

Currently when building a `Provider` package, users must [specify a `spec.controller.image`](https://doc.crds.dev/github.com/crossplane/crossplane/meta.pkg.crossplane.io/Provider/v1@v1.5.1#spec-controller-image), which dictates the image that Crossplane will use when creating the `Deployment` to run its controller. We typically publish two separate images for a `Provider`: the package image and the controller image. However, it is not required that the images be separate, and we could opt to use "fat" images that have both the package contents and controller binary in the same image. In that case, the `spec.controller.image` must reference itself, but if the image is pushed to multiple registries, the underlying contents have to be modified to update the controller image reference (or a `ControllerConfig` has to be referenced to override the underlying controller image at runtime).

### How could Crossplane help solve your problem?

The package manager could opt to make the controller image optional, and in the case it is not provided, use the package image itself as the controller image. This would not break any existing packages, and would still allow for specifying a separate controller image and / or overriding it with `ControllerConfig`.

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Updates the meta Provider package type to not require a controller image
to be specified. In the event that the field is omitted, the same image
that is used for the package will also be used for the controller.

This is backwards compatible with all existing provider packages.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Order of precedence for selecting controller image is as follows:

1. ControllerConfig specified image
2. Meta Provider package specified controller image
3. Package image used for install

Fixes #2757 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

I built and installed this Crossplane version in a local kind cluster:

```
🤖 (crossplane) k create ns crossplane-system
namespace/crossplane-system created
🤖 (crossplane) kind load docker-image crossplane/crossplane:v1.6.0-rc.0.99.g1f840122.dirty
Image: "crossplane/crossplane:v1.6.0-rc.0.99.g1f840122.dirty" with ID "sha256:af210f345a711fb043648f096de1132cf6b7b42e8c9c0af48e89aa1c24016d97" not yet present on node "kind-control-plane", loading...
🤖 (crossplane) helm install crossplane -n crossplane-system _output/charts/crossplane-1.6.0-rc.0.99.g1f840122.dirty.tgz --set packageCache.sizeLimit=50Mi
```

> Note that package cache size had to be increased due to the fact that the package image we are installing also has the full controller binary in it as well.

Installed a "fat" package for `provider-aws` (contains both the `package.yaml` and the provider controller:
```
🤖 (crossplane) kubectl crossplane install provider hasheddan/provider-aws-fat:v0.0.2
```

Verified package is successfully installed and controller is running:
```
🤖 (crossplane) k get pkg
NAME                                                    INSTALLED   HEALTHY   PACKAGE                             AGE
provider.pkg.crossplane.io/hasheddan-provider-aws-fat   True        True      hasheddan/provider-aws-fat:v0.0.2   19m
🤖 (crossplane) k get pkgrev
NAME                                                                         HEALTHY   REVISION   IMAGE                               STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/hasheddan-provider-aws-fat-6ae095a00184   True      1          hasheddan/provider-aws-fat:v0.0.2   Active                               19m
🤖 (crossplane) k get pods -n crossplane-system
NAME                                                       READY   STATUS    RESTARTS   AGE
crossplane-b569bfdd5-2rcwz                                 1/1     Running   0          17m
crossplane-rbac-manager-d575645d7-xb2kx                    1/1     Running   0          20m
hasheddan-provider-aws-fat-6ae095a00184-5c87dcff45-8lxn4   1/1     Running   0          17m
```

Installed a "traditional" provider package as well for good measure:
```
🤖 (crossplane) k get pkg
NAME                                                    INSTALLED   HEALTHY   PACKAGE                             AGE
provider.pkg.crossplane.io/crossplane-provider-gcp      True        True      crossplane/provider-gcp:master      8s
provider.pkg.crossplane.io/hasheddan-provider-aws-fat   True        True      hasheddan/provider-aws-fat:v0.0.2   20m
🤖 (crossplane) k get pkgrev
NAME                                                                         HEALTHY   REVISION   IMAGE                               STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/crossplane-provider-gcp-3a85e58512a4      True      1          crossplane/provider-gcp:master      Active                               12s
providerrevision.pkg.crossplane.io/hasheddan-provider-aws-fat-6ae095a00184   True      1          hasheddan/provider-aws-fat:v0.0.2   Active                               20m
🤖 (crossplane) k get pods -n crossplane-system
NAME                                                       READY   STATUS    RESTARTS   AGE
crossplane-b569bfdd5-2rcwz                                 1/1     Running   0          19m
crossplane-provider-gcp-3a85e58512a4-57f854fb98-kht9z      1/1     Running   0          61s
crossplane-rbac-manager-d575645d7-xb2kx                    1/1     Running   0          22m
hasheddan-provider-aws-fat-6ae095a00184-5c87dcff45-8lxn4   1/1     Running   0          19m
```

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by muvaf — APPROVED** [review]
Thanks @hasheddan !

**Comment by muvaf** [comment]
@hasheddan do you know if the package manager will clean up the pulled images after it's done deploying? If not, fat images might end up using a lot of disk/memory space depending on how that mechanism is implemented in the library we use.

**Comment by hasheddan** [comment]
@muvaf just commented on issue, we cache the whole image today, but I intend to only pull and cache the layer with package contents in the future so using fat images would not impact cache. https://github.com/crossplane/crossplane/issues/2757#issuecomment-991802639

**Review by muvaf — APPROVED** [review]
We just synced with @hasheddan offline and he'll open a separate issue about what changes we'd like to make to caching mechanism.

**Pull request merged**
