### PR TITLE
Add a one-pager guiding Function build tooling

### PR DESCRIPTION
**Pull request by negz**
### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/4796

I think as we build templates for languages like Go, Python, and TypeScript it will be useful to have a framework/philosophy for our patterns and tooling choices. The ultimate goal here is to make building a Function in a language you already know and work with regularly a familiar, unintimidating experience.

See https://github.com/crossplane/function-template-go/pull/23 for a reference implementation.

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [ ] ~Run `make reviewable` to ensure this PR is ready for review.~
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Comment by TerjeLafton** [comment]
Very nice! I really agree with the mindset of keeping functions as simple as possible.

But I would like to add that good scaffolding shouldn't be a replacement for good documentation. Not that I think that it is what is going to happen, I just feel like it has a tendency to happen in IT.

We have recently been developing both a provider and a function, and while it has been a lot of fun, it was usually hard to get started because of the scaffolding. The templates have you jump right into it, and it can be overwhelming for a new user trying to get started, especially if the documentation for the template is limited.

This might be an unpopular opinion, but I am not sure the template should even include CI, linting and things like that. It's great if the documentation says you should have linting, and it can be suggested both tools and configuration, but the scaffolding should be kept minimal.

**Comment by JonasKs** [comment]
I completely agree with @TerjeLafton here (which might be obvious since we're working together on writing functions and providers), and therefor disagree with @stevendborrelli. 

I think a `makefile`, and the `build`-submodule is bad thing. It's very hard to understand, and as a newcommer to the ecosystem it feels like makefiles and templates have been created instead of documentation, instead of an addition to it. 

When we wanted to build using `podman` in our own pipelines, we couldn't find any documentation of what needed to be done, or how to do it. The only thing we could find was the [make -j2 build.all](https://github.com/crossplane/provider-template/blob/main/.github/workflows/ci.yml#L236) command. @TerjeLafton set out on a mission to de-cypher it, and you can see the result here:  
image

This is not a good DX.

In my opinion, docs should be written like [FastAPI does it](https://fastapi.tiangolo.com/tutorial/first-steps/), and then templates and makefiles can come after - but the target audience for templates/makefiles should not be first timers/beginners. We found it very hard, since a lot of code is generated, and the makefiles(and `build` submodule) took us days to understand. We wished there was a tutorial or documentation that took us through it all from start instead. 

We'll definitely contribute with docs when our project has come to a more mature state.

**Comment by negz** [comment]
@TerjeLafton, @JonasKs - Thanks for the feedback! I definitely don't intend for this to be a stand-in for documentation. I agree we need both.

@stevendborrelli Would it help if the commands needed to lint, test, build etc a Function appeared in the `README`?

**Comment by negz** [comment]
> This might be an unpopular opinion, but I am not sure the template should even include CI, linting and things like that. It's great if the documentation says you should have linting, and it can be suggested both tools and configuration, but the scaffolding should be kept minimal.

@TerjeLafton I could be convinced to drop linting. Personally though I do think our Go linter config at least helps catch real bugs, not just style things, so it is likely to result in folks writing less buggy Functions faster.

For CI, I think we need to set a direction. My expectation is that pushing a Function to xpkg.upbound.io to get it listed in https://marketplace.upbound.io will be a pretty common requirement, so I kinda want to have that be smooth and somewhat opinionated. FWIW the current CI setup is basically a no-op if you don't create an `XPKG_ACCESS_ID` secret in your GitHub repo. It will just lint, test, and build everything and attach the `xpkg` files to your GitHub workflow output without pushing anything anywhere.

**Review by jbw976 — COMMENTED** [review]
This is pretty reasonable to me @negz! The feedback so far is fairly valid too and I'm seeing the high level themes fall into two camps:

* give developers granular commands that they can easily understand, enhance their productivity, and easily get to a high quality artifact
* automate as much as possible (e.g. with `make`) so developers don't have to think about the build details and can just focus on their code and getting that shipped ASAP

The spirit of both of these are valid and I'm wondering if there's a happy intermediate ground. Even though I like everything the crossplane `make` file automates for us, I agree that it's very challenging for just about anyone to understand, troubleshoot, or extract useful information out of it, e.g., fine grained commands to reuse in isolation.

My instincts so far is that the happy middle ground could be:

* provide all the useful (i.e. real world) commands for building/testing/publishing in the README of the templates - developers can use these locally with reasonable productivity and high understanding of the build process
  * perhaps these can be scripted a bit too, but not with `make`.
* codify the golden paths for CI in GitHub actions - this provides productive repeatable automation for shipping high quality artifacts

One potential gap I see right now is another type of "middle ground" - the e2e testing scenario in between:

* `go run`, `go test`
* CI publishing of production ready artifacts for real world usage

Is there a story for that scenario, where the developer can easily and build a test image locally on their laptop to test in their local cluster?

**Comment by TerjeLafton** [comment]
>For CI, I think we need to set a direction. My expectation is that pushing a Function to xpkg.upbound.io to get it listed in https://marketplace.upbound.io/ will be a pretty common requirement, so I kinda want to have that be smooth and somewhat opinionated. FWIW the current CI setup is basically a no-op if you don't create an XPKG_ACCESS_ID secret in your GitHub repo. It will just lint, test, and build everything and attach the xpkg files to your GitHub workflow output without pushing anything anywhere.

I think all of this depends on what documentation is available. Like @JonasKs said, it would be really nice to have better documentation for both how to create a Provider and a Function; either from scratch or with very minimal scaffolding, kind of like the FastAPI docs he linked.
Could this be available on `docs.crossplane.io` as a `tutorial` section, maybe? This is even something we would love to contribute to!

If these docs are available like described above, I think it would be totally fine to have a full fledged template with opinionated CI and linting, which can be really nice for those who are creating their nth function. 

Neither of these should exist alone, but they usually complement each other very well. 
* Good documentation for new users to learn and see just how easy it is
* Good template for experienced users who just needs to get started with their project

**Comment by pedjak** [comment]
> As someone building functions, the lack of a Makefile is frustrating. I create a pull request and it comes back with a bunch of linting and "gci" errors that I could have resolved locally. gci in particular will rewrite the import order of many .go files.

@stevendborrelli I have proposed something like what you are describing in https://github.com/crossplane/function-template-go/pull/16 please have a look. @JonasKs Makefile in that PR is just a tiny wrapper around multi-stage Dockerfile, just to make it simpler to invoke it. I agree with you that we should not include build submodule.

**Comment by negz** [comment]
My feeling is that a Makefile should be opt-in. For the template everyone starts from, less is probably better.

It's totally reasonable for a function to adopt the whole build submodule if the authors want to. For example I could see us doing this for something like function-patch-and-transform, where the majority of maintainers are folks who use that build submodule everywhere else.

**Comment by negz** [comment]
So we've had a few folks build functions, in Go, so far. I've also started experimenting with Python in https://github.com/negz/function-auto-python. Based on these experiences I'm feeling pretty good about what is proposed here. Unless we think it's way off the mark my preference would be to merge it and iterate.

**Comment by negz** [comment]
> Is there a story for that scenario, where the developer can easily and build a test image locally on their laptop to test in their local cluster?

@jbw976 Is `crossplane beta render` covering that scenario well enough? I've also updated the Go template repo README to include instructions on how to locally build a package: https://github.com/crossplane/function-template-go

**Comment by jbw976** [comment]
yes @negz I think the scenario of building a package to run on a local cluster is covered well enough now - I think when I made that comment initially we didn't really have the instructions in place for how to build the package, but now we do and it seems sufficient enough for when you wanna go past what `render` can currently and use a local test cluster via a package.

**Review by jbw976 — APPROVED** [review]

**Review by phisco — APPROVED** [review]
I agree with the approach, at least as a starting point, we can evolve it in the future if needed.

**Pull request merged**
