### PR TITLE
resource configuration via helm

### PR DESCRIPTION
**Pull request by arturrez**
Signed-off-by: Artur <artur@upbound.io>

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation] and [examples].
- [ ] Reported all new error conditions into the log or as an event, as
  appropriate.

For more about what we believe makes a pull request complete, see our
[definition of done].

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[definition of done]: https://github.com/crossplane/crossplane/tree/master/design/one-pager-definition-of-done.md

[skip ci]

### CODE REVIEW

**Comment by arturrez** [comment]
@jbw976  thank you for the feedback
* documentation has been updated.
* I used `helm install --dry-run` and also verified it by `helm lint` as it's part of the Jenkins job triggered per every PR

**Comment by jbw976** [comment]
Looks like `make check-diff` failed in the CI, can you try running that locally @arturrez?
https://jenkinsci.upbound.io/blue/organizations/jenkins/crossplane%2Fcrossplane%2Fbuild/detail/PR-1387/13/pipeline

**Comment by jbw976** [comment]
`make reviewable` would be even better as per the PR checklist in the description :)

**Comment by jbw976** [comment]
CI looks green now, great! One more thing @arturrez, can you please squash these into a single commit with a descriptive message? that makes more sense when looking in the history of the repo. 

Part of the PR checklist:

> Ensured this PR contains a neat, self documenting set of commits.

CI will be skipped after you do that, so we won't have to wait for the full cycle again.  Thank you!

**Comment by arturrez** [comment]
@jbw976  squashed into single commit with message `resource configuration via helm`

**Comment by jbw976** [comment]
Great, thanks for the follow up and the contribution to crossplane @arturrez! 🚀

**Pull request merged**
