### PR TITLE
[release-0.12] Prep docs for 0.12 release

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

This updates all snippet links to point to the release-0.12 branch, but
does not bump any of the provider or templating controller versions as
they are not being released on the same cadence as Crossplane v0.12.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by muvaf** [comment]
I think this is needed, too. Sorry for doing it that late :( https://github.com/crossplane/crossplane/pull/1607

**Comment by hasheddan** [comment]
@muvaf no worries! Do you want to get #1607 merged and then cherry-pick it over?

**Comment by muvaf** [comment]
@hasheddan it's merged now. Do I cherry-pick it to `release-0.12` branch?

**Comment by hasheddan** [comment]
@muvaf I can either do it in this PR, or you can open a separate PR with the cherry-pick. If you choose the latter, could you go ahead and approve this one?

**Comment by hasheddan** [comment]
@muvaf cherry pick added :+1:

**Pull request merged**
