### PR TITLE
docs: changing gympass adopters to wellhub company

### PR DESCRIPTION
**Pull request by caiofralmeida**
### Description of your changes

Gympass has been rebranded and is now Wellhub. We are updating the adopter's documentation.

Fixes # 

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [ ] ~Run `earthly +reviewable` to ensure this PR is ready for review.~
- [ ] ~Added or updated unit tests.~
- [ ] ~Added or updated e2e tests.~
- [ ] ~Linked a PR or a [docs tracking issue] to [document this change].~
- [ ] ~Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Review by turkenh — APPROVED** [review]
Thanks for the update!

**Review by turkenh — COMMENTED** [review]
@caiofralmeida would you mind signing off your commit to get [DCO action](https://github.com/crossplane/crossplane/pull/5887/checks?check_run_id=28865881635) passed?

**Review by jbw976 — APPROVED** [review]
Nice, thanks for keeping this up to date as your business evolves and grows @caiofralmeida!! 💪

**Comment by caiofralmeida** [comment]
Sorry to be late Guys, I think it's fixed now.

Thanks a lot.

**Comment by jbw976** [comment]
Perfect @caiofralmeida, thanks again!! 🙇‍♂️

**Pull request merged**
