### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by edalonso**
Signed-off-by: Eduardo Alonso <eduardo.alonso@disashop.com>

### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by jbw976** [comment]
Awesome @edalonso, thank you for making this contribution! We're merging these PRs in the order they were opened, so after #3730 is merged then I'll ping back on this PR for the next steps to get it merged in :)

**Comment by edalonso** [comment]
@jbw976 perfect. Let me know and I will update my PR

**Review by jbw976 — APPROVED** [review]

**Comment by jbw976** [comment]
Thanks again for sharing your crossplane adoption with us @edalonso, the community really appreciates it!! 🙇

**Comment by edalonso** [comment]
Thanks to you for the awesome product!!!

**Pull request merged**
