### PR TITLE
Enhanced `multiply` of transform `math` type to support `float64`

### LINKED ISSUE #3059: Enhance `multiply` of transform `math` type with support of `float64`
### What problem are you facing?

Currently  `multiply` of transform `math` type is limited to work with `int` and `int64` only.

If we try the constructs like

```
    - fromFieldPath: "status.maxConnPerSku"
      toFieldPath: "spec.forProvider.criteria[0].threshold"
      transforms:
      - type: convert
        convert:
          toType: float64
      - type: math
        math:
          multiply: 90
```

we will encounter patching failure of
```
 "reason": "ComposeResources", "message": "cannot render composed resource from resource template at index 3: cannot apply the patch at index 4: transform at index 1 returned error: math transform could not resolve: input is required to be a number for math transformer"}
```

In other words, `multiply` does not work with decimals on both sides of the equation: both inputs and multiplication factors are required to be integer only. 

It is seriously limiting in cases we need to deal with decimal values coming from source fields and/or multiply by a non-integer value like e.g. `1.05` or `0.9`

### How could Crossplane help solve your problem?

Enable `multiply` to support `float64`

Related code: https://github.com/crossplane/crossplane/blob/b49ddde2627ac732c53cae4a683024253cfe81b0/apis/apiextensions/v1/composition_transforms.go#L121-L137

### PR DESCRIPTION
**Pull request by Vrashabh-Sontakke**
### Description of your changes

Enabled `multiply` of transform type `math` to support `float64` without colluding with the API conventions.  
Added error reporting that is consistent with the codebase

Fixes #3059 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

`make`, `make e2e` and `make submodule` ran successfully without any errors

### CODE REVIEW

**Comment by Vrashabh-Sontakke** [comment]
`make reviewable` failing on my machine, probably cause of memory/cpu limitaions while `golangci-lint` process

**Comment by Vrashabh-Sontakke** [comment]
@ytsarev

**Comment by Vrashabh-Sontakke** [comment]
This PR is a DCO signed copy of my old deleted PR #3660

**Comment by Vrashabh-Sontakke** [comment]
> This PR is a DCO signed copy of my old deleted PR #3660

@ytsarev sorry for deleting the old PR, had to DCO Sign the commits.

**Review by ytsarev — CHANGES_REQUESTED** [review]
@Vrashabh-Sontakke generally, you can avoid PR deletion/recreation by git force push to the branch. 

Unfortunately, local tests are not enough in this case, and this issue is more tricky than it seems.

Please perform end-to-end tests with the Composition example from the original https://github.com/crossplane/crossplane/issues/3059 report, it will clarify a lot

**Comment by Vrashabh-Sontakke** [comment]
@ytsarev I even tried `make` and `make reviewable` in github codespaces, still getting same error while running `make reviewable`. The golang lint process is failing.

**Comment by jeanduplessis** [comment]
@Vrashabh-Sontakke Could you try installing `diffutils` package (for example `brew install diffutils` if on macOS). There's a known upstream issue: https://github.com/golangci/golangci-lint/issues/3087#issuecomment-1307442667

**Comment by Vrashabh-Sontakke** [comment]
> @Vrashabh-Sontakke Could you try installing `diffutils` package (for example `brew install diffutils` if on macOS). There's a known upstream issue: [golangci/golangci-lint#3087 (comment)](https://github.com/golangci/golangci-lint/issues/3087#issuecomment-1307442667)

let's try that

**Comment by phisco** [comment]
Shouldn't this update the [ResolveMath](https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/composition_transforms.go#L120) function instead?

**Comment by phisco** [comment]
superseded by https://github.com/crossplane/crossplane/pull/3989

**Pull request closed without merging**
