### PR TITLE
Bump Postgresql version in the documentation samples

### PR DESCRIPTION
**Pull request by ytsarev**
### Description of your changes

Affected Azure examples are using the retired 9.6 version.

Bump them to the supported version.

See https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions

Signed-off-by: Yury Tsarev <yury@upbound.io>

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Instantiating `postgresqlserver.database.azure.crossplane.io` with version 11

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by Piotr1215** [comment]
This is a nice catch @ytsarev , maybe also bumping the versions in AWS example would be helpful, to avoid the warning that the version is outdated in the AWS console :thinking: ?

**Comment by ytsarev** [comment]
@Piotr1215 thanks for suggestion, apparently just in time
```
Note
Deprecation of PostgreSQL 9.6 is scheduled for April 26, 2022. For more information, see [Deprecation of PostgreSQL version 9.6](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.DBVersions.Deprecation96).
```
I will amend the PR

**Comment by ytsarev** [comment]
@Piotr1215 bumped for AWS and GCP samples

**Comment by Piotr1215** [comment]
Awesome @ytsarev, I'm happy it was a timely observation. This deprecation message in clout consoles wasn't helping with a great user experience.

**Review by hasheddan — APPROVED** [review]
Thanks @ytsarev! Looks like AWS snippets were already using newer versions 👍🏻

**Pull request merged**
