### PR TITLE
template stacks: allow authors to specify controller image

### PR DESCRIPTION
**Pull request by muvaf**
### Description of your changes

This PR allows template stack authors to pin down the templating controller image they'd like. If not provided, it falls back to the default value on Crossplane helm chart.

Fixes https://github.com/crossplane/crossplane/issues/1291

### How has this code been tested?

* Crossplane master with minimal azure with and without `engine.controllerImage`
* This PR with minimal azure with and without `engine.controllerImage`

It's backward compatible.

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.
- [x] Updated any relevant [documentation] and [examples].
- [x] Reported all new error conditions into the log or as an event, as
  appropriate.

For more about what we believe makes a pull request complete, see our
[definition of done].

[documentation]: https://github.com/crossplane/crossplane/tree/master/docs
[examples]: https://github.com/crossplane/crossplane/tree/master/cluster/examples
[definition of done]: https://github.com/crossplane/crossplane/tree/master/design/one-pager-definition-of-done.md

### CODE REVIEW

**Comment by muvaf** [comment]
> Do we have a concrete use-case for this?

Yes, as author of the stack, I'd like to be sure of the behavior that I want is exactly what happens. Think of it like go mod dependencies; we're pinning them down for getting the same binary everywhere. Without this PR, the deciding factor is whatever Crossplane version happens to be deployed in the cluster, which is not something you'd want because it could be old/new/buggy version of templating controller, not the one you tested against.

**Comment by negz** [comment]
Would this allows folks who otherwise might not have RBAC permissions to run pods to do so? Or put otherwise, what could a malicious party do if they were able to specify their own template controller image?

**Comment by muvaf** [comment]
> Would this allows folks who otherwise might not have RBAC permissions to run pods to do so? Or put otherwise, what could a malicious party do if they were able to specify their own template controller image?

@negz The RBACs are applied like any other stack. Currently, they would be able to use whatever image they want when they build a normal stack, meaning someone with `*StackInstall` permissions can actually run any pod they want but it'd be constrained with RBAC they defined in `app.yaml`. In template stacks, instead of `install.yaml`, users would specify the image in `behavior.yaml`. So, there is not much of a change in terms of RBACs.

**Comment by muvaf** [comment]
@negz if you're onboard, could you merge this?

**Pull request merged**
