### PR TITLE
Adds Gympass as an Adopters

### PR DESCRIPTION
**Pull request by caiofralmeida**
### Description of your changes

Adding Gympass as an adopter in the documentation.

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by jbw976 — COMMENTED** [review]
Awesome to see this addition @caiofralmeida, thanks for making it! 🙇 

Can you update your commit to sign-off on the DCO? I've opened a recent PR you may find helpful to add a bit more guidance about the how/why of the DCO, including some helpful git commands: #3716 

We've gotten a few of these great adopters list additions today, and we're trying to take them in order. Unfortunately, there will be a small merge conflict for you to resolve when the PRs ahead of yours get merged in.

I'll ping you back on this PR when it's a good time to resolve conflicts, thank you for your patience! 💪

**Comment by caiofralmeida** [comment]
@jbw976 Yes, I can :)

No problem, count on me to resolve these conflicts.

Thank you!

**Comment by jbw976** [comment]
alrighty @caiofralmeida, now that #3710 has been merged, it's your turn to resolve the merge conflict.  Please fetch the latest from master and then resolve the conflict by adding your entry to the bottom of the list.

Let me know if you need any help at all, thank you!! 🙇

**Comment by caiofralmeida** [comment]
Fixed @jbw976, thank you!

Let me know if I should fix something else.

**Review by jbw976 — APPROVED** [review]
Perfect, this looks all good now @caiofralmeida, thanks again for this contribution, your support of the project, and for handing the merge conflict! 👏 🙇

**Review by hasheddan — APPROVED** [review]

**Pull request merged**
