### PR TITLE
Fix CRD Required Schema

### LINKED ISSUE #2003: Generated CRDs are Missing the `required` Field in the Structural Schema
### What happened?

I just hit a small issue with `openAPIV3Schema` for XRDs: In the code we only copy the `.Properties` field of the `spec` schema to the final CRD schema.
This makes it impossible to make properties of the `spec` schema required because the `.Required` field at this level is ignored.
Also the `spec` field itself is not required and could therefore be completely missing.

Same goes for the generated Claim CRDs.

https://github.com/crossplane/crossplane/blob/master/internal/xcrd/crd.go#L94
https://github.com/crossplane/crossplane/blob/master/internal/xcrd/crd.go#L81

### How can we reproduce it?

Using the XRD example from the [docs](https://crossplane.io/docs/v0.14/introduction/composition.html#define-your-composite-resource), the generated CRD won't have the fields `.spec` and `.spec.parameters` marked as required, even though the schema in the XRD does so.

### What environment did it happen in?
Crossplane version: v0.14.0

### PR DESCRIPTION
**Pull request by srueg**
### Description of your changes

Fixes #2003

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`make test`

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by negz** [comment]
Thanks @srueg! Would you mind doing a little manual testing on this one; i.e. make sure you can create a composite resource claim and composite resource with and without required fields?

**Review by negz — APPROVED** [review]
This looks good to me - happy to merge once you ack that it works fine when tested manually.

**Comment by srueg** [comment]
Alright, I did a quick test based on the examples (XRD, XR & XRC) in the [docs](https://crossplane.io/docs/v0.14/introduction/composition.html) and it all worked as expected. 🎉

**Review by hasheddan — APPROVED** [review]

**Comment by negz** [comment]
@srueg Thanks! Looks like this needs a rebase - once that's done I'll merge.

**Pull request merged**
