### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by wanghong230**
### Description of your changes

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
Awesome! Thanks @wanghong230! Would you mind updating your commit with DCO according to the guidance [here](https://github.com/crossplane/crossplane/tree/master/contributing#certificate-of-origin).

**Comment by wanghong230** [comment]
> Awesome! Thanks @wanghong230! Would you mind updating your commit with DCO according to the guidance [here](https://github.com/crossplane/crossplane/tree/master/contributing#certificate-of-origin).

Done

**Review by jeanduplessis — CHANGES_REQUESTED** [review]
@wanghong230 please note we are listing entries to the table in the order they are added rather than alphabetical. Would you mind updating the entry to be at the bottom of the list.

**Review by jeanduplessis — APPROVED** [review]

**Comment by jbw976** [comment]
Thank you for this contribution @wanghong230, and we appreciate your follow through already to address the few small issues.

We're merging these PRs in the order that they were submitted, so yours will be after #3722 - once that PR is merged, you'll have a merge conflict to resolve.  I'll ping you when it's your turn to do the merge conflict dance 😂 

let me know if you want me to handle the conflict when it's time, I'm happy to do that also!

**Comment by jbw976** [comment]
OK @wanghong230, now that #3722 has been merged, it's your turn to resolve the merge conflict and make your contribution at the end of the list.

Please let me know if you'd like me to take care of it directly, happy to help out here! Thank you! :)

**Comment by wanghong230** [comment]
> OK @wanghong230, now that #3722 has been merged, it's your turn to resolve the merge conflict and make your contribution at the end of the list.
> 
> Please let me know if you'd like me to take care of it directly, happy to help out here! Thank you! :)

My 2 cents, the choice of non-alphabetical order is costing more engineering hours for this. alphabetical order is not perfect, but results in fewer conflicts to coordinate. The community is forcing both the contributors and also the maintainers to do those expansive communications.

**Review by jbw976 — APPROVED** [review]

**Comment by jbw976** [comment]
Thanks for resolving the merge conflicts @wanghong230 and for the feedback on your experience.  I think the multiple conflicts we're experiencing right now are more of a bootstrapping problem since we just created this adopters list and multiple people are wanting to join it at the same time. I think this problem largely goes away after we get to steady state and the rate of additions drops significantly.

I'm happy to proactively resolve the merge conflicts for folks, that is a fairly inexpensive operation for me since I've done that workflow on this file already, so that could help future contributors.

Thanks again for the feedback and for sharing your Crossplane adoption with the rest of the community! 🙇

**Pull request merged**
