### PR TITLE
Add missing word

### PR DESCRIPTION
**Pull request by plumbis**
Signed-off-by: Pete Lumbis <pete@upbound.io>

### Description of your changes
Adds the word "the" that was missing. This was caught in [docs site PR #208](https://github.com/crossplane/crossplane.github.io/pull/208)

Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by negz** [comment]
Would it make sense for these to be backports of the PR to master? That creates some relationship between the commits - we have a bit of automation that can open the PRs for you (see the back port entry in the checklist).

**Comment by plumbis** [comment]
Sure? I don't know how the auto backporting works and my limited attempts in the past have not been successful.

**Comment by hasheddan** [comment]
@plumbis you can put labels on the `master` one and see if it works.

**Review by hasheddan — CHANGES_REQUESTED** [review]
backports have been merged across all branches -- this PR and its siblings can be closed 👍🏻

**Pull request closed without merging**
