### PR TITLE
Change 'Compute' to 'Computing' in CNCF

### PR DESCRIPTION
**Pull request by nickbeaugie**
Signed-off-by: Nick Beaugié <5430452+nickbeaugie@users.noreply.github.com>

CNCF stands for "Cloud Native Computing Foundation" (not "Compute")
See the home page: https://www.cncf.io

### Description of your changes

Just a documentation change. Hopefully not a big deal, but will mean that newbies to your page don't think "what the heck" when they read that.

I have:

- [ X] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested
N/A - it's a pure documentation change.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
Thanks @nickbeaugie!

**Comment by nickbeaugie** [comment]
@hasheddan - you are welcome. It looks like I am not authorized to merge this PR. One of the checks has passed, the others have been "skipped" (I guess as this is only documentation).

What happens now. Do one of you merge the PR?

**Comment by hasheddan** [comment]
> What happens now. Do one of you merge the PR?

@nickbeaugie a maintainer must merge every PR, but in this case, we need steering committee approval first (README.md is covered by steering code owners). cc @jbw976

**Review by jbw976 — APPROVED** [review]
LGTM, thanks for this catch @nickbeaugie! This looks aligned with the guidance in `#6` of https://github.com/cncf/foundation/blob/main/website-guidelines.md :)

**Pull request merged**
