### PR TITLE
fix: remove ignored FromEnvironmentFieldPath for environment patches

### LINKED ISSUE #4080: Ignored `FromEnvironmentFieldPath` patch type in `spec.environment.patches`
### What happened?

The Composition's CRD is configured to accept patches of type `FromEnvironmentFieldPath` to be defined in `spec.environment.patches`, see [here](https://github.com/crossplane/crossplane/blob/c4031aab55c729df6af6a9e4d7b39e3cdd2dcce9/apis/apiextensions/v1/composition_environment.go#L119), but then the [ApplyEnvironmentPatches](https://github.com/crossplane/crossplane/blob/c4031aab55c729df6af6a9e4d7b39e3cdd2dcce9/internal/controller/apiextensions/composite/composition_patches.go#L64) function is not including them.

Given that patches in that context are only meant to be applied between the Composite Resource and the `in-memory` environment, the `FromEnvironmentFieldPath` patch would be semantically equivalent to the supported `ToCompositeFieldPath` type, so either we remove it from the APIs or we just remap it to a `ToCompositeFieldPath` in code. I'd lean toward the removal option given that that API is in alpha and it's actually confusing, but I'm open to discuss it.

### How can we reproduce it?

N.A. just looking at the code is enough.

### What environment did it happen in?
Crossplane version: v1.12.1

### PR DESCRIPTION
**Pull request by phisco**
### Description of your changes

Fixes #4080.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested
N.A. just removing a previously ignored but supported parameter.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by phisco** [comment]
Could be worth backporting to 1.12, WDYT?

**Review by hasheddan — COMMENTED** [review]
> Could be worth backporting to 1.12, WDYT?

@phisco I think I would lean towards not backporting. Though this is alpha functionality and we reserve the right to change / break it from one release to another, I generally think of that policy being applicable to minor versions rather than patches. Would defer to @negz here though.

**Review by negz — APPROVED** [review]
Yeah I wouldn't worry about back porting this.

**Review by MisterMX — APPROVED** [review]
Makes sense to me. Thanks a lot @phisco!

**Pull request merged**
