### PR TITLE
WIP enable insight into constructed environment

### PR DESCRIPTION
**Pull request by pedjak**
### Description of your changes

WIP demonstration how we could enable users to get more insights into the composition reconciliation process.

The main purpose of this PR is to trigger the conversation on #4660

How to play with this:
* build and deploy Crossplane from this PR with environment configs enabled
* add `alpha.crossplane.io/dev-mode: env` to a claim
* eventually the counterpart composite is equipped with `alpha.crossplane.io/env-bootstrap` annotation containing the environment data before the composition was processed

Signed-off-by: Predrag Knezevic <predrag.knezevic@upbound.io>

### CODE REVIEW

**Comment by pedjak** [comment]
@ytsarev @bobh66 you can use e2e manifests to quickly see the outcome:

* `kubectl apply -f apply -f test/e2e/manifests/apiextensions/environment/setup`
* `kubectl apply -f apply -f test/e2e/manifests/apiextensions/environment/default/setup`
* create claim with the new annotation:

```yaml
apiVersion: example.org/v1alpha1
kind: SQLInstance
metadata:
  name: example
  namespace: default
  annotations:
    alpha.crossplane.io/dev-mode: env
  labels:
    stage: prod
spec:
  parameters:
    storageGB: 10
```

Eventually, the environment content is published as `alpha.crossplane.io/env-bootstrap` annotation on the composite:

```yaml
apiVersion: example.org/v1alpha1
kind: XSQLInstance
metadata:
  annotations:
    alpha.crossplane.io/dev-mode: env
    alpha.crossplane.io/env-bootstrap: |-
      {
        "apiVersion": "internal.crossplane.io/v1alpha1",
        "complex": {
          "a": "b",
          "c": {
            "d": "e",
            "f": "2"
          }
        },
        "kind": "Environment"
      }
```

An alternative place for publishing would be somewhere under `status.devmode`. In parallel to that we could also generate events/logs.

**Comment by negz** [comment]
If we write to XR status, and once we resolve https://github.com/crossplane/crossplane/issues/4600, I believe this could be implemented as a Function. That could give us some extra flexibility - i.e. I could imagine being able to choose whether you wanted to log the environment (in the Function logs), emit it as an event, write it to status, etc.

**Comment by bobh66** [comment]
If the annotation reconciles downward from the claim it will enable debugging on all nested composites, which could be several dozen or more.  That may or may not be desirable?

**Comment by pedjak** [comment]
> If the annotation reconciles downward from the claim it will enable debugging on all nested composites, which could be several dozen or more. That may or may not be desirable?

From what I could see in [the code](
https://github.com/crossplane/crossplane/blob/master/internal/controller/apiextensions/composite/composition_render.go#L121), we do not pass any annotations from claim to MRs, only a few labels. Ofcourse, if needed, we could do that as well, so that we could debug the whole chain.

**Comment by jankaacc** [comment]
Very happy to see this feature, we spent a lot of time debugging what is in the runtime environment. Although the provided [example](https://github.com/crossplane/crossplane/blob/master/test/e2e/manifests/apiextensions/environment/default/setup/composition.yaml) could be a bit extended.

The most difficult part with debugging environment configs is when we are dynamically patching values to the environment in one resource and then we are relying on those values in another resource.

This is a short example of what I am talking about:

Lets say we have existing EnvironmentConfig like

```yaml
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: example-environment-1
data:
  devEnv: staging
```

Then in Composition we are selecting this Env Config and we do some bidirectional patching

Selection:

```yaml
...
spec:
  environment:
    environmentConfigs:
      - ref:
          name: example-environment-1
...
```

Patching

```yaml
resources:
    - name: resource1
      base:
        ...
      patches:
        - type: ToEnvironmentFieldPath
          fromFieldPath: status.someValueAfterMRCreation
          toFieldPath: myMRProp
    
    - name: resource2
      base:
        ...
      patches:
        - type: CombineFromEnvironment
           combine:
             variables:
               - fromFieldPath: devEnv
               - fromFieldPath: myMRProp
             strategy: string
             string:
               fmt: '%s-%s'
           toFieldPath: spec.forProvider.name
           fromFieldPath:
             policy: Required
```

The problem we were often facing was that `resource2` was not created because `status.someValueAfterMRCreation` was missing. 
It was time-consuming to debug the problem as we needed to check dependent resources and their statuses, If we could see the run time environment it would have saved us a lot of time. 
So very happy to see this functionality coming, but I would test this with an example which is patching the environment dynamically.

**Comment by phisco** [comment]
We still have to merge and take a decision for https://github.com/crossplane/crossplane/pull/5061, but the overall agreement is to lean more and more on functions. In the meantime support for `environment` was added to Functions, and therefore this could either become a topic for `function-patch-and-transform`, if we still want to have more visibility inside the single function, or as suggested  by @negz [above](https://github.com/crossplane/crossplane/pull/4702#issuecomment-1739914337), the goal of a dedicated `debug` Function.

So, as agreed with @pedjak, this PR can be closed.

**Pull request closed without merging**
