### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by natereid72**
### Description of your changes

Fix doc typo

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

No testing required

[contribution process]: https://git.io/fj2m9

Signed-off-by: Nate Reid <natereid@protonmail.com>

### CODE REVIEW

**Review by hasheddan — CHANGES_REQUESTED** [review]
Thanks for fixing this @natereid72! We require [sign-off on all commits](https://docs.pi-hole.net/guides/github/how-to-signoff/), which should get DCO passing :) Could you update with that and also populate the PR template body? (no testing required for this type of change, but a small description is still nice)

**Comment by natereid72** [comment]
@hasheddan Just updated the title to signed-off-by format. Don't know if that actually fixes it though. When I get back to desk, I can pull it down and try from cli.

**Comment by hasheddan** [comment]
@natereid72 you'll need to sign off on the commit specifically, title can be used to describe the change 👍🏻 Link in my last comment has some helpful tips

**Comment by natereid72** [comment]
closing, will recreate with signed commit

**Comment by natereid72** [comment]
closed, will recreate with signed commit.

**Pull request closed without merging**
