### PR TITLE
Move everything in pkg to internal directory

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

In preparation for the v1.0 release of crossplane, all packages are
being moved to the internal directory as anything that should be able to
be imported by other packages should move to crossplane-runtime.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

`make build`

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by negz** [comment]
@hasheddan Any idea why coverage dropped so much? I vaguely recall that the makefile explicitly runs tests in a specific test of dirs - one of which is probably `pkg`.

**Comment by hasheddan** [comment]
@negz good catch! We do manually declare static packages, I'll update in `Makefile` 👍

**Comment by khos2ow** [comment]
@hasheddan I believe you missed this section in `.golangci.yml`:

```yaml
...
  skip-dirs:
  - "pkg/client/clientset"
...
```

**Comment by hasheddan** [comment]
Thanks @khos2ow! Surprised that it didn't pop up with any failures :sweat_smile: Since it didn't I'll just remove the skip rather than updating it :+1:

**Comment by khos2ow** [comment]
That's true, and the fact that those code are being generated there's a good chance that there won't be any warning/error anyways. But I think it's still safe to keep them around to prevent any random surprises. For instance [this](https://github.com/hasheddan/crossplane/blob/internalized/internal/client/clientset/versioned/scheme/register.go#L33) doesn't have a GoDoc and technically a violation (being ignored by golangci).

**Review by negz — APPROVED** [review]

**Pull request merged**
