### PR TITLE
DO NOT MERGE: Demonstrate no-op CI false positive

### PR DESCRIPTION
**Pull request by wonderflow**
How to reproduce?

1. give a broke commit (without signoff)
2. signoff and force push

### CODE REVIEW

**Comment by wonderflow** [comment]
@negz

**Comment by hasheddan** [comment]
Interesting.. seems like `detect-noop` should return with the status of the identical run :thinking:

**Comment by negz** [comment]
Thanks @wonderflow! I'll see if we can fix this behaviour in the GitHub action upstream, or at least raise a bug.

**Comment by negz** [comment]
A fix for this has been merged upstream. I've raised https://github.com/crossplane/crossplane/issues/1893 to track deploying the fix once it is released.

**Pull request closed without merging**
