### PR TITLE
adding Renault in ADOPTERS list

### PR DESCRIPTION
**Pull request by smileisak**
### Description of your changes

Adding Renault to ADOPTERS file.

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Only documentation added.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by jeanduplessis — APPROVED** [review]

**Review by jbw976 — APPROVED** [review]
Awesome, thank you for making this addition to the adopters list @smileisak!! 🎉

**Comment by jbw976** [comment]
We've got a few of these additions to the adopters list today, so we'll be taking them in the order that they were opened.

Unfortunately, that means a small merge conflict to handle - #3709 is next in line, so I would maybe wait till after that is merged and then handle the conflict after that.

Looks like this can be done from Github also by a maintainer, so let me know if you want me to try that experience out too - never used it before ;)

**Comment by jbw976** [comment]
now that #3709 is in, it's your turn to handle a merge conflict @smileisak!

Please let me know if you need any help with resolving the merge conflict, I am happy to take care of that myself and prevent any headaches for you 😇

**Comment by smileisak** [comment]
@jbw976 it should be ok now.

**Review by jeanduplessis — APPROVED** [review]

**Pull request merged**
