### PR TITLE
`init` - add option to select branch/tag 

### PR DESCRIPTION
**Pull request by lsviben**
### Description of your changes

Noticed during the creation of the [configuration-template](https://github.com/crossplane/configuration-template) that its annoying that the `init` command just clones the `main` branch without any options to change. It makes it difficult to test the `init` commands NOTES.txt and `init.sh` script during development.

With this option, you can choose a tag or branch name to clone from. It should make developing templates easier.

Example:
```bash
~/go/crossplane/_output/bin/darwin_arm64/crank beta xpkg init conf-temp https://github.com/lsviben/configuration-template -d conf12 --ref-name v0.1.0
Initialized package "conf-temp" in directory "/Users/lsviben/test/t/conf12" from https://github.com/lsviben/configuration-template/tree/2b121e1a57b4e8b9a0ca4907b2ed2cb6a829ccff (HEAD)

A template for writing a Configuration (https://docs.crossplane.io/v1.14/concepts/packages).

To use this template:
1. Replace the name, metadata in crossplane.yaml to reflect your Configuration.
2. Add dependencies in crossplane.yaml.
3. Update the sample CompositeResourceDefinition and Composition in the `apis/`
   directory to reflect the API you're designing for your platform, and optionally add more if needed.
4. Add/Update examples in the `examples/` directory.
5. Update the `README.md`, to be about your Configuration!

To build and push your Configuration to a registry, run the following commands
using the Crossplane CLI:

`crossplane xpkg build`
(Optionally) `crossplane xpkg login`
`crossplane xpkg push your-org/your-repo:v1.0.0`

Check the README.md for more information and have fun building your Configuration!
```

```bash
~/go/crossplane/_output/bin/darwin_arm64/crank beta xpkg init conf-temp https://github.com/lsviben/configuration-template -d conf13 --ref-name skelly
Initialized package "conf-temp" in directory "/Users/lsviben/test/t/conf13" from https://github.com/lsviben/configuration-template/tree/2b121e1a57b4e8b9a0ca4907b2ed2cb6a829ccff (skelly)

A template for writing a Configuration (https://docs.crossplane.io/v1.14/concepts/packages).

To use this template:
1. Replace the name, metadata in crossplane.yaml to reflect your Configuration.
2. Add dependencies in crossplane.yaml.
3. Update the sample CompositeResourceDefinition and Composition in the `apis/`
   directory to reflect the API you're designing for your platform, and optionally add more if needed.
4. Add/Update examples in the `examples/` directory.
5. Update the `README.md`, to be about your Configuration!

To build and push your Configuration to a registry, run the following commands
using the Crossplane CLI:

`crossplane xpkg build`
(Optionally) `crossplane xpkg login`
`crossplane xpkg push your-org/your-repo:v1.0.0`

Check the README.md for more information and have fun building your Configuration!
```

I have: 

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- ~[] Added or updated unit tests.~
- ~[] Added or updated e2e tests.~
- [x] Linked a PR or a [docs tracking issue] to [document this change].
- ~[] Added `backport release-x.y` labels to auto-backport this PR.~

Need help with this checklist? See the [cheat sheet].

[contribution process]: https://github.com/crossplane/crossplane/tree/master/contributing
[docs tracking issue]: https://github.com/crossplane/docs/issues/new
[document this change]: https://docs.crossplane.io/contribute/contribute
[cheat sheet]: https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet

### CODE REVIEW

**Comment by lsviben** [comment]
I know its late, but I wonder if its worth including this in v1.15 as it would help folks working on template post-init hooks.

**Review by phisco — APPROVED** [review]
I would be fine having this back-ported, @jbw976 I'll leave to you the last call.

**Review by jbw976 — APPROVED** [review]
Cool, this functionality seems to work when I just tested, and it would have been nice to have yesterday while testing the new content you were adding to https://github.com/lsviben/configuration-template/tree/skelly  that wasn't in the main branch yet 😂 

This is very low risk, so I'm not against backporting it too.

**Comment by lsviben** [comment]
> Cool, this functionality seems to work when I just tested, and it would have been nice to have yesterday while testing the new content you were adding to https://github.com/lsviben/configuration-template/tree/skelly that wasn't in the main branch yet 😂

My pain yesterday made me do this, actually did it during working on that. You could say its first-hand dev experience improvements 😁

**Pull request merged**
