### PR TITLE
test/e2e: print related object events in kubectl style

### PR DESCRIPTION
**Pull request by sttts**
### Description of your changes

Use the `kubectl events` printer code to show events for related objects on failed e2e tests.

This style:
Bildschirmfoto 2023-10-16 um 14 43 53

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] ~~Added or updated unit **and** E2E tests for my change.~~
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] ~~Added `backport release-x.y` labels to auto-backport this PR, if necessary.~~
- [ ] ~~Opened a PR updating the [docs], if necessary.~~

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

**Review by phisco — APPROVED** [review]
Much better, thanks @sttts!

**Comment by sttts** [comment]
@phisco can you retry the test for me? :D

**Comment by phisco** [comment]
@sttts any particular reason? E2Es are not required to merge a PR, it's fine if there is a single red step, more so on this PR which is actually improving the way we visualise failures due to flaky e2es.

**Comment by sttts** [comment]
True. Coming from projects where they are requird and ignoring them is very very bad.

**Comment by phisco** [comment]
We introduced e2es not so long ago, we definitely have a lot of work to get to the confidence we need to set them as required, agreed

**Review by pedjak — APPROVED** [review]

**Pull request merged**
