### PR TITLE
Add pizza order example link

### PR DESCRIPTION
**Pull request by lrascao**
### Description of your changes

Was curious about the pizza example, would be nicer to just be able to click and read it instead of having to search

I have:

- [X] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

**Review by jbw976 — COMMENTED** [review]
Cool @lrascao, thanks for adding this detail here to make it easier for future readers to find it :)

While you're at it - how do you feel about linking the other items in this list too?  e.g. SQL server at https://github.com/crossplane-contrib/provider-sql and helm releases at https://github.com/crossplane-contrib/provider-helm/ ?

**Comment by lrascao** [comment]
Sure thing, pushed

**Review by jbw976 — APPROVED** [review]
awesome, thank you for adding those other links too @lrascao! 💪

**Review by hasheddan — COMMENTED** [review]
@lrascao would you mind backporting this update to the `release-1.2` branch as well? :) Directions on how to do so can be found [here](https://crossplane.io/docs/v1.2/contributing/release-process.html#bug-fixes-in-release-branch).

**Comment by lrascao** [comment]
sure, https://github.com/crossplane/crossplane/pull/2283

**Pull request merged**
