### PR TITLE
Added a bare YAML to deploy crossplane

### PR DESCRIPTION
**Pull request by gyliu513**
Signed-off-by: Guang Ya Liu <gyliu513@gmail.com>

### Description of your changes

Fixes https://github.com/crossplane/crossplane/issues/1750

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by gyliu513** [comment]
This file was generated by following command:

```
helm install crossplane --namespace crossplane-system crossplane-alpha/crossplane --dry-run
```

**Review by hasheddan — COMMENTED** [review]
Thanks for taking this on @gyliu513! A few thoughts on maintaining a "static" YAML deployment manifest:
- I generally am hesitant to maintain multiple ways to deploy something because it increases the opportunity for them to diverge. However, it doesn't seem entirely unreasonable that someone does not want to use Helm or does not have access to in their operating environment, so I think there is some merit here.
- If we were to maintain this, do you think it should be a `kustomize` chart so that there is still some available configuration? I would potentially buy an argument against it because it could be harder (potentially impossible) to maintain compatible configuration. However, `kustomize` allows users to build overlays on a base, so it seems like we could just provider the base and allow consumers to overlay as they see fit. I believe this is what @muvaf was suggesting on the linked issue.
- Regardless of direction, I think this manifest should definitely be generated automatically by our code generation / build processes. Happy to help out on that if needed :)

**Comment by muvaf** [comment]
> This file was generated by following command
> `helm install crossplane --namespace crossplane-system crossplane-alpha/crossplane --dry-run`

Agree with @hasheddan that it'd be great if we had this command as part of our `make generate` target that will generate those YAMLs. We'd probably need to add version tag to that command so that it generates from the correct chart in `master` and `alpha` channels. Separately, I'd opt for `cluster/deploy` as folder instead of `cluster/deploy/yaml` because it's kind of apparent that they are `yaml` files.

**Comment by gyliu513** [comment]
Thanks, +1 to leverage `make generate` to enable this, let me close my PR.

**Pull request closed without merging**
