### PR TITLE
fix(CompositionRevisions): Import composition types from v1

### LINKED ISSUE #3274: Ensure full compatibility between Composition and CompositionRevision
### What happened?

Compositions and CompositionRevisions are made of different Go structs in `apis/apiextensions/v1` and `apis/apiextensions/v1alpha1`. This frequently leads to a desynchronization between both because changes in Compositions are not propagated to CompositionRevisions:

* #2825
* #2836
* #3113
* #3130

Consistency with Compositions for CompositionRevisions should be ensured before bumping them to v1beta1 (#2656).

This gets relevant every time the Composition API is extended.

### How could Crossplane help solve your problem?

There are multiple ways to ensure compatibility between Composition and CompositionRevisions:

* Automatically copy Go types from `v1` to `v1alpha1` using a script Go code generator.
* Let `v1alpha1` import Composition structs from `v1`.
* Create a third API struct to which `v1` and `v1alpha1` types are converted to during reconcile. K8s does something similar with it's own [apiextensions](`https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions).

### PR DESCRIPTION
**Pull request by MisterMX**
### Description of your changes

This ensures compatibility between Compositions and CompositionRevisions by importing all structures from v1 into v1alpha1 instead of copying them.

Fixes #3274

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

Unit tests

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by bobh66 — COMMENTED** [review]
I'm not proficient enough in go or in the codebase to make any specific comments, but strictly from a code style/programming standpoint, if a composition revision is just a composition with a revision number, then this makes sense to me, as it is clear and concise and maintains consistency between the Composition and the CompositionRevision.  I understand the reluctance to mix v1 and v1alpha1, but hopefully CompositionRevision will reach v1 and it will cease to be a problem.   From that point on I would expect them to proceed in lockstep version-wise. 

My .02 - I can make this an approval if you think it qualifies.

**Comment by negz** [comment]
I'm going to "sleep on" this for the weekend but I'm inline to just go ahead and merge. It seems like a violation to share API types, but it would make life a lot easier (and avoid a lot of bugs), and as you both point out this is a bit of a special case where one type is a mirror of another.

**Review by hasheddan — COMMENTED** [review]
I noticed in https://github.com/crossplane/crossplane/issues/3274 that the idea of generating copies of the structures in `v1` was discussed. While this would have the same effect today, I do like that any changes to `v1` would be surfaced as actual diffs in `v1alpha1`. Was there is a particular reason why we didn't pursue that path?

**Comment by MisterMX** [comment]
> I noticed in #3274 that the idea of generating copies of the structures in `v1` was discussed. While this would have the same effect today, I do like that any changes to `v1` would be surfaced as actual diffs in `v1alpha1`. Was there is a particular reason why we didn't pursue that path?

Sadly, I don't know of any kind of utility to clone code from another package.

It would also make Revision -> Composition conversion more complex because with different types you cannot use `DeepCopy` for it.

**Comment by negz** [comment]
> Maybe it makes sense to overthink the design of CompositionRevision again

@MisterMX Personally I would prefer not to make CompositionRevision an opaque bag of JSON - I dropped a comment on that issue.

FWIW I believe @ezgidemirel is planning to tackle https://github.com/crossplane/crossplane/issues/2656 within the next week or two. This won't obviate this issue completely, but if CompositionRevision becomes beta and on-by-default we can at least simplify a bit in that we won't need to round-trip from revision -> composition when reconciling. We'll only need to be able to make revisions from a composition, and all reconcile logic (patches and transforms etc) will move to the revision type.

**Comment by negz** [comment]
I'm going to close this since we're reluctant to proceed with the approach. Definitely copying at build time would be ideal, but as far as I know there's no tool to do this.

**Pull request closed without merging**
