### PR TITLE
feat(adopters): added deutsche kreditbank ag

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: Christopher Paul Haar <christopherpaul.haar@dkb.de>

### Description of your changes
added deutsche kreditbank ag to adopters list

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by jeanduplessis — APPROVED** [review]

**Review by hasheddan — APPROVED** [review]
🎉

**Comment by jbw976** [comment]
Awesome @haarchri, thank you for adding your org to this list, and thanks for all the support and contributions you've made to Crossplane over the years 😅 🤩 

We're merging these PRs in the order that they were submitted, so yours will be after #3712 - once that PR is merged, you'll have a merge conflict to resolve.  I'll ping you when it's your turn to do the merge conflict dance 😂 

let me know if you want me to handle the conflict when it's time, I'm happy to do that also!

**Comment by jbw976** [comment]
alright @haarchri, now that #3712 has been merged, it's your turn to resolve a merge conflict!

I've done this for other PRs recently, so let me know if you want me to take care of it myself - happy to be useful here :)

otherwise, let me know when the merge conflict is taken care of, and we'll this one merged too!

**Comment by haarchri** [comment]
@jbw976  done!

**Review by jbw976 — APPROVED** [review]
perfect, thanks for following up on the merge conflicts @haarchri!! 💪

**Pull request merged**
